// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtQw7J4bTkkc32qscD49e3c7E_n6gUW0',
    appId: '1:23381028292:web:893ae7eb5397b0921d0891',
    messagingSenderId: '23381028292',
    projectId: 'sneakerx-6dbc9',
    authDomain: 'sneakerx-6dbc9.firebaseapp.com',
    storageBucket: 'sneakerx-6dbc9.appspot.com',
    measurementId: 'G-587FKERKJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtv457SQoS-CZshsi8ha9pKBX9LPTIqQ',
    appId: '1:23381028292:android:ac7be728aef68bb01d0891',
    messagingSenderId: '23381028292',
    projectId: 'sneakerx-6dbc9',
    storageBucket: 'sneakerx-6dbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmnO1pCspFiK5v4BtVJHMsTC-sqRhf0yo',
    appId: '1:23381028292:ios:4682cc5e85f666901d0891',
    messagingSenderId: '23381028292',
    projectId: 'sneakerx-6dbc9',
    storageBucket: 'sneakerx-6dbc9.appspot.com',
    iosBundleId: 'com.bigetron.sneakerx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmnO1pCspFiK5v4BtVJHMsTC-sqRhf0yo',
    appId: '1:23381028292:ios:4682cc5e85f666901d0891',
    messagingSenderId: '23381028292',
    projectId: 'sneakerx-6dbc9',
    storageBucket: 'sneakerx-6dbc9.appspot.com',
    iosBundleId: 'com.bigetron.sneakerx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEtQw7J4bTkkc32qscD49e3c7E_n6gUW0',
    appId: '1:23381028292:web:3d63d8720b916f611d0891',
    messagingSenderId: '23381028292',
    projectId: 'sneakerx-6dbc9',
    authDomain: 'sneakerx-6dbc9.firebaseapp.com',
    storageBucket: 'sneakerx-6dbc9.appspot.com',
    measurementId: 'G-0Z0TKCSZHJ',
  );
}
